name: C++ Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt-get install -y libboost-all-dev
    - name: make
      run: make test
    - name: test
      run: build/test
